info:
  version: 1.0.1
  description: TSCTSF initial local configuration

configuration:
  tsctsfName: TSCTSF # the name of this TSCTSF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.50 # IP used to register to NRF
    bindingIPv4: 127.0.0.50  # IP used to bind the service
    port: 8000              # port used to bind the service
    tls: # the local path of TLS key
      # pem: cert/pcf.pem # PCF TLS Certificate
      # key: cert/pcf.key # PCF TLS Private key
  nrfUri: http://127.0.0.10:8000  # a valid URI of NRF
  serviceNameList:   # the SBI services provided by this PCF, refer to TS 29.507
    - ntsctsf_timesynchronization # Ntsctsf_TimeSynchronization
logger: # log output setting
  enable: true # true or false
  level: trace # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
