/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package TimeSynchronization

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// TimeSynchronizationExposureSubscriptions - Creates a new subscription to notification of capability of time synchronization service resource
func TimeSynchronizationExposureSubscriptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
